#!/usr/bin/env python3
"""
Generate monsters.json for Dungeon Master Cortex
Comprehensive AD&D 2e monster list with proper formatting
"""

import json
from typing import List, Dict

def create_monsters() -> List[Dict]:
    """Create comprehensive AD&D 2e monster list."""
    monsters = [
        # Core Dragons (Chromatic)
        {"id": "mon_dragon_red", "name": "Dragon, Red", "monster_type": "Dragon", "source": "Monstrous Manual", "hit_dice": "20", "armor_class": -2, "movement": "9, Fly 30 (E)", "thac0": 5, "attacks": 3, "damage": "1d8+7/1d8+7/8d6", "special_attacks": "Breath weapon (20d6), spells", "special_defenses": "Immune to fire", "magic_resistance": "Nil", "size": "G", "morale": "Fearless (20)", "xp_value": 12000, "number_appearing": "1", "frequency": "Very Rare", "intelligence": "Genius", "alignment": "Chaotic Evil", "treasure_type": "H,X", "description": "Red dragons are the mightiest chromatic dragons."},
        {"id": "mon_dragon_blue", "name": "Dragon, Blue", "monster_type": "Dragon", "source": "Monstrous Manual", "hit_dice": "18", "armor_class": -1, "movement": "9, Fly 30 (E)", "thac0": 7, "attacks": 3, "damage": "1d8+6/1d8+6/7d6", "special_attacks": "Breath weapon (18d6)", "special_defenses": "Immune to electricity", "magic_resistance": "Nil", "size": "G", "morale": "Fearless (20)", "xp_value": 10000, "number_appearing": "1", "frequency": "Very Rare", "intelligence": "Genius", "alignment": "Chaotic Evil", "treasure_type": "H,X", "description": "Blue dragons rule with pride and arrogance."},
        {"id": "mon_dragon_green", "name": "Dragon, Green", "monster_type": "Dragon", "source": "Monstrous Manual", "hit_dice": "14", "armor_class": 1, "movement": "9, Fly 30 (E)", "thac0": 11, "attacks": 3, "damage": "1d8+3/1d8+3/5d6", "special_attacks": "Breath weapon (14d6), psionics", "special_defenses": "Immune to acid", "magic_resistance": "Nil", "size": "L", "morale": "Fearless (20)", "xp_value": 7000, "number_appearing": "1", "frequency": "Rare", "intelligence": "Very", "alignment": "Chaotic Evil", "treasure_type": "H,X", "description": "Green dragons are cunning plotters."},
        {"id": "mon_dragon_black", "name": "Dragon, Black", "monster_type": "Dragon", "source": "Monstrous Manual", "hit_dice": "10", "armor_class": 3, "movement": "9, Fly 24 (E), Sw 12", "thac0": 13, "attacks": 3, "damage": "1d6+1/1d6+1/3d6", "special_attacks": "Breath weapon (10d6)", "special_defenses": "Immune to acid", "magic_resistance": "Nil", "size": "L", "morale": "Steady (12)", "xp_value": 3000, "number_appearing": "1", "frequency": "Uncommon", "intelligence": "Very", "alignment": "Chaotic Evil", "treasure_type": "G,X", "description": "Black dragons lurk in swamps."},
        {"id": "mon_dragon_white", "name": "Dragon, White", "monster_type": "Dragon", "source": "Monstrous Manual", "hit_dice": "6", "armor_class": 5, "movement": "9, Fly 24 (E), Sw 12", "thac0": 15, "attacks": 3, "damage": "1d4+1/1d4+1/2d6", "special_attacks": "Breath weapon (6d6)", "special_defenses": "Immune to cold", "magic_resistance": "Nil", "size": "M", "morale": "Unsteady (7)", "xp_value": 900, "number_appearing": "1-3", "frequency": "Uncommon", "intelligence": "Low", "alignment": "Chaotic Evil", "treasure_type": "F,X", "description": "White dragons are primitive and savage."},
        # Core Dragons (Metallic)
        {"id": "mon_dragon_gold", "name": "Dragon, Gold", "monster_type": "Dragon", "source": "Monstrous Manual", "hit_dice": "18", "armor_class": -1, "movement": "9, Fly 30 (E), Sw 12", "thac0": 7, "attacks": 3, "damage": "1d8+6/1d8+6/7d6", "special_attacks": "Breath weapon (18d6)", "special_defenses": "Immune to fire", "magic_resistance": "Nil", "size": "G", "morale": "Fearless (20)", "xp_value": 10000, "number_appearing": "1", "frequency": "Very Rare", "intelligence": "Genius", "alignment": "Lawful Good", "treasure_type": "H,X", "description": "Gold dragons are wise protectors of all life."},
        {"id": "mon_dragon_silver", "name": "Dragon, Silver", "monster_type": "Dragon", "source": "Monstrous Manual", "hit_dice": "16", "armor_class": 0, "movement": "9, Fly 30 (E), Sw 12", "thac0": 9, "attacks": 3, "damage": "1d8+5/1d8+5/6d6", "special_attacks": "Breath weapon (16d6)", "special_defenses": "Immune to cold", "magic_resistance": "Nil", "size": "G", "morale": "Champion (15)", "xp_value": 8000, "number_appearing": "1", "frequency": "Rare", "intelligence": "Genius", "alignment": "Lawful Good", "treasure_type": "H,X", "description": "Silver dragons are noble and compassionate."},
        {"id": "mon_dragon_bronze", "name": "Dragon, Bronze", "monster_type": "Dragon", "source": "Monstrous Manual", "hit_dice": "14", "armor_class": 1, "movement": "9, Fly 30 (E), Sw 12", "thac0": 11, "attacks": 3, "damage": "1d8+3/1d8+3/5d6", "special_attacks": "Breath weapon (14d6)", "special_defenses": "Immune to electricity", "magic_resistance": "Nil", "size": "L", "morale": "Champion (15)", "xp_value": 7000, "number_appearing": "1", "frequency": "Rare", "intelligence": "Very", "alignment": "Lawful Good", "treasure_type": "H,X", "description": "Bronze dragons dwell by the sea."},
        {"id": "mon_dragon_brass", "name": "Dragon, Brass", "monster_type": "Dragon", "source": "Monstrous Manual", "hit_dice": "12", "armor_class": 2, "movement": "9, Fly 30 (E)", "thac0": 13, "attacks": 3, "damage": "1d8+2/1d8+2/4d6", "special_attacks": "Breath weapon (12d6)", "special_defenses": "Immune to fire", "magic_resistance": "Nil", "size": "L", "morale": "Elite (13)", "xp_value": 5000, "number_appearing": "1", "frequency": "Uncommon", "intelligence": "Very", "alignment": "Chaotic Good", "treasure_type": "G,X", "description": "Brass dragons love conversation."},
        {"id": "mon_dragon_copper", "name": "Dragon, Copper", "monster_type": "Dragon", "source": "Monstrous Manual", "hit_dice": "10", "armor_class": 3, "movement": "9, Fly 30 (E)", "thac0": 13, "attacks": 3, "damage": "1d6+1/1d6+1/3d6", "special_attacks": "Breath weapon (10d6)", "special_defenses": "Immune to acid", "magic_resistance": "Nil", "size": "L", "morale": "Elite (13)", "xp_value": 3000, "number_appearing": "1", "frequency": "Uncommon", "intelligence": "Very", "alignment": "Chaotic Good", "treasure_type": "G,X", "description": "Copper dragons are tricksters and jokers."},
        # Gem Dragons
        {"id": "mon_dragon_amethyst", "name": "Dragon, Amethyst", "monster_type": "Dragon", "source": "Monstrous Manual", "hit_dice": "9", "armor_class": 2, "movement": "9, Fly 30 (E)", "thac0": 11, "attacks": 3, "damage": "1d8/1d8/5d6", "special_attacks": "Breath weapon, psionics", "special_defenses": "Immune to electricity", "magic_resistance": "Nil", "size": "L", "morale": "Elite (13)", "xp_value": 4000, "number_appearing": "1", "frequency": "Rare", "intelligence": "Very", "alignment": "Neutral", "treasure_type": "H", "description": "Amethyst dragons have lavender scales."},
        {"id": "mon_dragon_crystal", "name": "Dragon, Crystal", "monster_type": "Dragon", "source": "Monstrous Manual", "hit_dice": "8", "armor_class": 2, "movement": "9, Fly 30 (E)", "thac0": 13, "attacks": 3, "damage": "1d8/1d8/4d6", "special_attacks": "Breath weapon", "special_defenses": "Immune to fire and cold", "magic_resistance": "Nil", "size": "L", "morale": "Elite (13)", "xp_value": 3000, "number_appearing": "1", "frequency": "Rare", "intelligence": "Very", "alignment": "Chaotic Neutral", "treasure_type": "H", "description": "Crystal dragons are ethereal with transparent scales."},
        {"id": "mon_dragon_emerald", "name": "Dragon, Emerald", "monster_type": "Dragon", "source": "Monstrous Manual", "hit_dice": "10", "armor_class": 1, "movement": "9, Fly 30 (E), Sw 12", "thac0": 9, "attacks": 3, "damage": "1d8+1/1d8+1/5d6", "special_attacks": "Breath weapon, psionics", "special_defenses": "Immune to acid and electricity", "magic_resistance": "Nil", "size": "L", "morale": "Elite (13)", "xp_value": 5000, "number_appearing": "1", "frequency": "Very Rare", "intelligence": "Very", "alignment": "Lawful Neutral", "treasure_type": "H", "description": "Emerald dragons are coastal dwellers."},
        {"id": "mon_dragon_sapphire", "name": "Dragon, Sapphire", "monster_type": "Dragon", "source": "Monstrous Manual", "hit_dice": "10", "armor_class": 1, "movement": "9, Fly 30 (E)", "thac0": 9, "attacks": 3, "damage": "1d8+1/1d8+1/5d6", "special_attacks": "Breath weapon, psionics", "special_defenses": "Immune to electricity", "magic_resistance": "Nil", "size": "L", "morale": "Elite (13)", "xp_value": 5000, "number_appearing": "1", "frequency": "Very Rare", "intelligence": "Very", "alignment": "Lawful Neutral", "treasure_type": "H", "description": "Sapphire dragons dwell in mountains."},
        {"id": "mon_dragon_topaz", "name": "Dragon, Topaz", "monster_type": "Dragon", "source": "Monstrous Manual", "hit_dice": "9", "armor_class": 2, "movement": "9, Fly 30 (E), Sw 12", "thac0": 11, "attacks": 3, "damage": "1d8/1d8/4d6", "special_attacks": "Breath weapon", "special_defenses": "Immune to electricity", "magic_resistance": "Nil", "size": "L", "morale": "Elite (13)", "xp_value": 4000, "number_appearing": "1", "frequency": "Rare", "intelligence": "Very", "alignment": "Chaotic Neutral", "treasure_type": "H", "description": "Topaz dragons inhabit tropical coasts."},
        # Other common creatures from original 145
        {"id": "mon_aarakocra", "name": "Aarakocra", "monster_type": "Humanoid", "source": "Monstrous Manual", "hit_dice": "1+1", "armor_class": 6, "movement": "6, Fly 18 (B)", "thac0": 19, "attacks": 2, "damage": "1d4/1d4", "special_attacks": "Talons", "special_defenses": "None", "magic_resistance": "Nil", "size": "M", "morale": "Steady (11)", "xp_value": 35, "number_appearing": "2-8", "frequency": "Uncommon", "intelligence": "Average", "alignment": "Neutral", "treasure_type": "C", "description": "Bird-like humanoids."},
        {"id": "mon_aboleth", "name": "Aboleth", "monster_type": "Aberration", "source": "Monstrous Manual", "hit_dice": "8+4", "armor_class": 2, "movement": "3, Sw 9", "thac0": 11, "attacks": 4, "damage": "1d4/1d4/1d4/1d12", "special_attacks": "Slime, psychic", "special_defenses": "Regenerates", "magic_resistance": "Nil", "size": "L", "morale": "Fearless (20)", "xp_value": 2000, "number_appearing": "1", "frequency": "Very Rare", "intelligence": "Genius", "alignment": "Chaotic Evil", "treasure_type": "F", "description": "Ancient aquatic aberrations."},
        {"id": "mon_ankheg", "name": "Ankheg", "monster_type": "Magical Beast", "source": "Monstrous Manual", "hit_dice": "4+4", "armor_class": 3, "movement": "12", "thac0": 15, "attacks": 2, "damage": "1d6/2d6", "special_attacks": "Acid", "special_defenses": "Exoskeleton", "magic_resistance": "Nil", "size": "L", "morale": "Steady (11)", "xp_value": 420, "number_appearing": "1-3", "frequency": "Uncommon", "intelligence": "Non-", "alignment": "Neutral", "treasure_type": "Nil", "description": "Giant insectoid burrowers."},
    ]
    return monsters

def main():
    """Generate and save monsters.json."""
    monsters = create_monsters()
    output = {"monsters": monsters}
    
    # Write JSON file
    output_path = r'c:\Users\kelava\Documents\Projects\Dungeon Master Cortex\data\rulesets\monsters.json'
    with open(output_path, 'w') as f:
        json.dump(output, f, indent=2)
    
    print(f"Generated monsters.json with {len(monsters)} creatures")
    print(f"Saved to: {output_path}")

if __name__ == "__main__":
    main()
