using System;
using System.Diagnostics;
using System.Windows;
using DungeonMasterCortex.Services;

namespace DungeonMasterCortex.Views;

public partial class ActivationRequestDialog : Window
{
    private readonly LicenseService _license;

    public ActivationRequestDialog(LicenseService license)
    {
        _license = license;
        InitializeComponent();
    }

    private void BtnSendRequest_Click(object sender, RoutedEventArgs e)
    {
        string name = TxtName.Text.Trim();
        string email = TxtEmail.Text.Trim();
        string phone = TxtPhone.Text.Trim();

        if (string.IsNullOrWhiteSpace(name) || string.IsNullOrWhiteSpace(email) || string.IsNullOrWhiteSpace(phone))
        {
            TxtStatus.Text = "Status: Name, email, and phone are required.";
            MessageBox.Show("Name, email, and phone are required.", "Activation Request", MessageBoxButton.OK, MessageBoxImage.Warning);
            return;
        }

        if (!email.Contains("@", StringComparison.Ordinal) || !email.Contains('.', StringComparison.Ordinal))
        {
            TxtStatus.Text = "Status: Enter a valid email address.";
            MessageBox.Show("Enter a valid email address.", "Activation Request", MessageBoxButton.OK, MessageBoxImage.Warning);
            return;
        }

        string requestPayload = _license.GetActivationRequestPayload();
        if (_license.TrySendActivationRequestBySmtp(requestPayload, out string message, name, email, phone))
        {
            TxtStatus.Text = "Status: Activation request sent successfully.";
            MessageBox.Show(message, "Activation Request", MessageBoxButton.OK, MessageBoxImage.Information);
            DialogResult = true;
            Close();
            return;
        }

        // Fallback for machines without SMTP settings: copy payload and open default mail client.
        Clipboard.SetText(requestPayload);

        var smtpSettings = _license.GetSmtpSettings();
        string targetEmail = string.IsNullOrWhiteSpace(smtpSettings.ToEmail)
            ? "your activation support email"
            : smtpSettings.ToEmail.Trim();

        string subject = "Dungeon Master Codex Activation Request";
        string body = "Activation request generated by Dungeon Master Codex.%0D%0A%0D%0A"
            + $"Name: {Uri.EscapeDataString(name)}%0D%0A"
            + $"Email: {Uri.EscapeDataString(email)}%0D%0A"
            + $"Phone: {Uri.EscapeDataString(phone)}%0D%0A%0D%0A"
            + "Full Payload (for backend):%0D%0A"
            + Uri.EscapeDataString(requestPayload);

        TryOpenMailClient(targetEmail, subject, body);

        TxtStatus.Text = "Status: SMTP send failed. Full payload copied to clipboard for manual email.";
        MessageBox.Show(
            $"{message}\n\nSMTP may not be configured on this PC.\n\n"
            + "The full activation payload has been copied to your clipboard. "
            + $"Send it manually to {targetEmail}.",
            "Activation Request",
            MessageBoxButton.OK,
            MessageBoxImage.Warning);
    }

    private static void TryOpenMailClient(string targetEmail, string subject, string body)
    {
        try
        {
            string mailto = $"mailto:{targetEmail}?subject={Uri.EscapeDataString(subject)}&body={body}";
            Process.Start(new ProcessStartInfo(mailto) { UseShellExecute = true });
        }
        catch
        {
            // Ignore mail client launch failures; clipboard fallback is already in place.
        }
    }

    private void BtnClose_Click(object sender, RoutedEventArgs e)
    {
        Close();
    }
}
